name: Build and Push Image

on:
  schedule:
    # 毎日 09:00 JST
    - cron: "0 0 * * *"

  workflow_dispatch:

env:
  DOCKER_REGISTRY_NAME: ghcr.io
  DOCKER_IMAGE_NAME: ${{ github.repository }} # {username|org}/waterfall

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Set current datetime as env variable
        env:
          TZ: 'Asia/Tokyo'
        run: echo "RELEASE_DATE=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ env.RELEASE_DATE }}
          release_name: ${{ env.RELEASE_DATE }}
          body: |
            Daily Build and Release.
          draft: false
          prerelease: false

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Registry
        uses: docker/login-action@v1 
        with:
          registry: ${{ env.DOCKER_REGISTRY_NAME }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v2
        env:
          DOCKER_BUILDKIT: 1
        with:
          context: .
          push: true
          tags: ${{ env.RELEASE_DATE }}
          labels: ${{ env.RELEASE_DATE }}
          cache-from: ${{ env.DOCKER_REGISTRY_NAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest
          build-args: BUILDKIT_INLINE_CACHE=1